name: agronomist
description: A bilingual farmer-friendly diagnosis app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.11.0
  image: ^4.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.3
  
  # State & Inputs
  provider: ^6.1.2
  image_picker: ^1.1.2
  speech_to_text: ^7.0.0
  share_plus: ^10.0.2

  # Firebase
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.0
  firebase_storage: ^12.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/farm_bg.jpg
    - assets/models/labels.txt
    - assets/models/mobilenet_v2_crop.tflite

# l10n configuration
gen_l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations